version: '3.7'
services: 
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment: 
      ACCEPT_EULA: Y
      MSSQL_PID: Express
      SA_PASSWORD: P@ssw0rd
    ports: 
      - 1433:1433